// Wraps docs/apps-script-store.gs into an ES module the Worker can import.
//
// Workers may not evaluate code at runtime, so the store script is turned into a module at
// build time: its top-level functions and settings become the body of loadStore(), the
// Google services it uses arrive as parameters, and every function is returned. The script
// itself stays the single source of truth for both backends.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '..', 'docs', 'apps-script-store.gs'), 'utf8');
const functions = [...source.matchAll(/^function\s+([A-Za-z0-9_]+)\s*\(/gm)].map(m => m[1]);

const services = ['SpreadsheetApp', 'PropertiesService', 'CacheService', 'LockService',
	'UrlFetchApp', 'ContentService', 'HtmlService', 'Utilities', 'console'];

const out = `// GENERATED by build.mjs from docs/apps-script-store.gs - edit the script, not this file.
/* eslint-disable */
export function loadStore(google)
{
	const { ${services.join(', ')} } = google;
${source}
	return { ${functions.join(', ')} };
}
`;
mkdirSync(join(here, 'src', 'generated'), { recursive: true });
writeFileSync(join(here, 'src', 'generated', 'store-script.js'), out);
console.log('store-script.js: ' + functions.length + ' functions');
