// Wraps docs/apps-script-store.gs into an ES module the Worker can import.
//
// Workers may not evaluate code at runtime, so the store script is turned into a module at
// build time: its top-level functions and settings become the body of loadStore(), the
// Google services it uses arrive as parameters, and every function is returned. The script
// itself stays the single source of truth for both backends.
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(here, '..', 'docs', 'apps-script-store.gs'), 'utf8');
const functions = [...source.matchAll(/^function\s+([A-Za-z0-9_]+)\s*\(/gm)].map(m => m[1]);

const services = ['SpreadsheetApp', 'PropertiesService', 'CacheService', 'LockService',
	'UrlFetchApp', 'ContentService', 'HtmlService', 'Utilities', 'console'];

const out = `// GENERATED by build.mjs from docs/apps-script-store.gs - edit the script, not this file.
/* eslint-disable */
export function loadStore(google)
{
	const { ${services.join(', ')} } = google;
${source}
	return { ${functions.join(', ')} };
}
`;
mkdirSync(join(here, 'src', 'generated'), { recursive: true });
const target = join(here, 'src', 'generated', 'store-script.js');
// Only write a real change: wrangler dev watches this file, and rewriting it unchanged
// would trigger the build again, forever.
if (!existsSync(target) || readFileSync(target, 'utf8') !== out)
{
	writeFileSync(target, out);
}
console.log('store-script.js: ' + functions.length + ' functions');

// The clan logo and icon, embedded so the Worker serves them without separate hosting.
const assets = `// GENERATED by build.mjs from the project's images.
export const LOGO_PNG = '${readFileSync(join(here, '..', 'docs', 'clan-logo-bingo-full.png')).toString('base64')}';
export const ICON_PNG = '${readFileSync(join(here, '..', 'icon.png')).toString('base64')}';
`;
const assetsTarget = join(here, 'src', 'generated', 'assets.js');
if (!existsSync(assetsTarget) || readFileSync(assetsTarget, 'utf8') !== assets)
{
	writeFileSync(assetsTarget, assets);
}
