// Embeds the clan logo and icon into a module, so the Worker serves them without separate
// hosting. Runs before every deploy and test (wrangler.toml, package.json).
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const assets = `// GENERATED by build.mjs from the project's images.
export const LOGO_PNG = '${readFileSync(join(here, '..', 'docs', 'clan-logo-bingo-full.png')).toString('base64')}';
export const ICON_PNG = '${readFileSync(join(here, '..', 'icon.png')).toString('base64')}';
`;
mkdirSync(join(here, 'src', 'generated'), { recursive: true });
const target = join(here, 'src', 'generated', 'assets.js');
// Only write a real change: wrangler dev watches this file, and rewriting it unchanged
// would trigger the build again, forever.
if (!existsSync(target) || readFileSync(target, 'utf8') !== assets)
{
	writeFileSync(target, assets);
}
